services:
  grafana:
    image: grafana/grafana:13.0.1
    container_name: puda-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "bearsnas:100.87.23.102"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`demo.puda.co`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true

volumes:
  grafana_data:
